RBG_MATRIX_SUPPORTED = yes
RGBLIGHT_SUPPORTED = yes
BOOTMAGIC_ENABLE = no 
EXTRAKEY_ENABLE = yes

# Encoder
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

#OLED
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
OLED_TRANSPORT = i2c

#RGB
RGBLIGHT_ENABLE = yes
